name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 bandit pytest

      # Install package in editable mode (so imports work everywhere)
      - name: Install chroma_curator package (editable)
        run: |
          pip install -e .

      # Lint both package and CLI script
      - name: Lint with flake8
        run: |
          flake8 chroma_curator/ cli.py --max-line-length=100

      # Static analysis for security issues
      - name: Static security scan with Bandit
        run: |
          bandit -r chroma_curator/ cli.py

      # Ensure test_vectors.json exists before running tests
      - name: Ensure test_vectors.json exists
        run: |
          if [ ! -f tests/test_vectors.json ]; then
            echo "ERROR: tests/test_vectors.json is missing!"
            exit 1
          fi

      # Run all tests
      - name: Run unit tests
        run: |
          pytest tests/

      # Secret scanning with detect-secrets CLI
      - name: Check for secrets with detect-secrets
        run: |
          pip install detect-secrets
          detect-secrets scan > .secrets.baseline
          # This will print audit results, but not fail the build on findings (for fail-on-find, handle exit code)
          detect-secrets audit .secrets.baseline || exit 0
